clear all

plotFlag = false;

sourceDirectories = { ...
	'./Oblong/drll2/',...
	'./Oblong/foxd5/',...
	'./Oblong/gadd45ga/',...
	'./Oblong/iscub/',...
	'./Oblong/klf2b/',...
	'./Oblong/ripply1/',...
	'./Oblong/vamp2/',...
	'./Oblong/zgc_64022/',...
	'./Sphere/drll2/',...
	'./Sphere/foxd5/',...
	'./Sphere/gadd45ga/',...
	'./Sphere/iscub/',...
	'./Sphere/klf2b/',...
	'./Sphere/ripply1/',...
	'./Sphere/vamp2/',...
	'./Sphere/zgc_64022/',...
	'./Dome/drll2/',...
	'./Dome/foxd5/',...
	'./Dome/gadd45ga/',...
	'./Dome/iscub/',...
	'./Dome/klf2b/',...
	'./Dome/ripply1/',...
	'./Dome/vamp2/',...
	'./Dome/zgc_64022/',...
	'./30_Epiboly/drll2/',...
	'./30_Epiboly/foxd5/',...
	'./30_Epiboly/gadd45ga/',...
	'./30_Epiboly/iscub/',...
	'./30_Epiboly/klf2b/',...
	'./30_Epiboly/ripply1/',...
	'./30_Epiboly/vamp2/',...
	'./30_Epiboly/zgc_64022/',...
	'./50_Epiboly/drll2/',...
	'./50_Epiboly/foxd5/',...
	'./50_Epiboly/gadd45ga/',...
	'./50_Epiboly/iscub/',...
	'./50_Epiboly/klf2b/',...
	'./50_Epiboly/ripply1/',...
	'./50_Epiboly/vamp2/',...
	'./50_Epiboly/zgc_64022/'...
	};
extractTargetFolder = 'ExtractedStacks_Stages';
condInds = (1:(5.*8))';
condLabels = {...
	'Oblong_drll2','Oblong_foxd5','Oblong_gadd45ga','Oblong_iscub',...
	'Oblong_klf2b','Oblong_ripply1','Oblong_vamp2','Oblong_zgc:64022',...
	'Sphere_drll2','Sphere_foxd5','Sphere_gadd45ga','Sphere_iscub',...
	'Sphere_klf2b','Sphere_ripply1','Sphere_vamp2','Sphere_zgc:64022',...
	'Dome_drll2','Dome_foxd5','Dome_gadd45ga','Dome_iscub',...
	'Dome_klf2b','Dome_ripply1','Dome_vamp2','Dome_zgc:64022',...
	'Epi30_drll2','Epi30_foxd5','Epi30_gadd45ga','Epi30_iscub',...
	'Epi30_klf2b','Epi30_ripply1','Epi30_vamp2','Epi30_zgc:64022',...
	'Epi50_drll2','Epi50_foxd5','Epi50_gadd45ga','Epi50_iscub',...
	'Epi50_klf2b','Epi50_ripply1','Epi50_vamp2','Epi50_zgc:64022',...
	};
maxNumSeries = Inf;

skipList = [1:8,17:40]; % Directories to skip, for example if already done
% Leave empty array [] if all directories shoudl be processed.
% Current setting is to that all but the Sphere stage data are skipped.

% The channels must be assigned so that the they represent the following
% labels in the biological sample:
% Channel 1: Elongating Pol II, Pol II Ser2Phos
% Channel 2: Recruited Pol II, Pol II Ser5Phos
% Channel 3: Oligopaint DNA-FISH labeling of the gene of interest
useChannel_inds = [1,2,3];
numChannels = numel(useChannel_inds);
scaleChannels = {[-Inf,Inf],[-Inf,Inf],[-Inf,Inf]};

numDirs = numel(sourceDirectories);

for cc = 1:numDirs
    
	fprintf('Extracting image data from directory %d of %d\n',cc,numDirs)
	
	if ismember(cc,skipList)
		
		fprintf('On skip list, skipping to next directory.\n')
		
	else
		
		thisDir = sourceDirectories{cc};
		
		listing = rdir([thisDir,'*.nd2'],'~contains(name,''._'')');
		
		numFiles = numel(listing);
		
		imgCell = cell(numFiles,1);
		imgSizeCell = cell(numFiles,1);
		pixelSizeVec = cell(numFiles,1);
		zzStepVec = cell(numFiles,1);
		
		stackCounter = 0;
		mkdir(sprintf('./%s/Cond_%d',extractTargetFolder,cc))
		
		for ff = 1:numFiles
			
			fprintf('Extracting images from file %d of %d\n',ff,numFiles)
			
			combined_filepath = ...
				fullfile(listing(ff).name);
			
			[imgCell,imgSizeCell,...
				this_voxelSize_cell,seriesName_cell] = ...
				nd2read(combined_filepath,maxNumSeries);
			
			pixelSizeVec = cellfun(@(elmt)elmt(1),this_voxelSize_cell);
			zzStepVec = cellfun(@(elmt)elmt(3),this_voxelSize_cell);
			
			numImgs = numel(imgCell);
			for kk = 1:numImgs
				imgCell{kk} = imgCell{kk}(useChannel_inds);
			end
			
			if plotFlag
				
				for kk = 1:numImgs
					
					thisPixelSize = pixelSizeVec(kk);
					thisSize = imgSizeCell{kk};
					
					numChannels = numel(imgCell{kk});
					
					for cc_2 = 1:numChannels
						
						subplot(1,numChannels,cc_2)
						
						imagesc([0,thisSize(2)].*thisPixelSize,...
							[0,thisSize(1)].*thisPixelSize,...
							imgCell{kk}{cc_2}(:,:,ceil(thisSize(3)./2)),...
							scaleChannels{1})
						axis equal tight
						
						xlabel('x [\mum]')
						
						colormap((gray))
						
					end
					
					disp(sprintf( ...
						'Directory number %d, Condition %s, File %d/%d, Image %d/%d.', ...
						cc,condLabels{condInds(cc)},ff,numFiles,kk,numImgs))
					
					waitforbuttonpress
					
				end
				
			end
			
			% Apply exclusion indices
			keepInds = 1:numImgs;
			imgCell = imgCell(keepInds);
			imgSizeCell = imgSizeCell(keepInds);
			pixelSizeVec = pixelSizeVec(keepInds);
			zzStepVec = zzStepVec(keepInds);
			
			% --- saving of the retained images
			
			condName = condLabels{cc};
			condInd = condInds(cc);
			
			% Save all images into a separate file, but contained in a folder that
			% contains all images for this condition
			
			numImgs = numel(imgCell);
			for kk = 1:numImgs
				stackCounter = stackCounter+1;
				imgStack = imgCell{kk};
				imgSize = imgSizeCell{kk};
				pixelSize = pixelSizeVec(kk);
				zStepSize = zzStepVec(kk);
				save(sprintf('./%s/Cond_%d/Image_%d.mat',...
					extractTargetFolder,cc,stackCounter),...
					'imgStack','imgSize','pixelSize','zStepSize',...
					'condInd','condName')
			end
			
		end
		
	end
	
end